-- Staff salary loans (ខ្ចីប្រាក់ខែ): money lent to a staff member and paid back by a fixed
-- installment deducted from each payroll run until the loan is repaid (FRD 13 §2.6).
-- Unlike an advance (deducted in full at the next payday), a loan spans several runs.
--
-- Run once:  psql "$DATABASE_URL" -f backend/scripts/migrations/2026-10-07_staff_loans.sql
-- Safe to re-run.

BEGIN;

CREATE TABLE IF NOT EXISTS staff_loans (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_id    bigint        NOT NULL REFERENCES staff(id),
    principal   numeric(14,2) NOT NULL CHECK (principal > 0),
    currency    varchar(3)    NOT NULL CHECK (currency IN ('USD', 'KHR')),
    -- Deducted from each payroll run (capped by what is still owed and by the staff member's pay)
    installment numeric(14,2) NOT NULL CHECK (installment > 0),
    given_at    date          NOT NULL,
    wallet_id   bigint REFERENCES wallets(id),
    -- The expense invoice posted when the money was handed over
    invoice_id  bigint REFERENCES invoices(id),
    -- open: still owed · repaid: fully paid back · void: cancelled before any repayment
    status      varchar(20)   NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'repaid', 'void')),
    note        text,
    created_by  bigint REFERENCES users(id),
    created_at  timestamptz   NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS staff_loans_staff_idx ON staff_loans (staff_id, status);

-- One row per loan per paid payroll line; written when the run is paid, deleted when it is voided.
-- Outstanding = principal - SUM(amount).
CREATE TABLE IF NOT EXISTS staff_loan_repayments (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    loan_id         bigint        NOT NULL REFERENCES staff_loans(id),
    payroll_item_id bigint        NOT NULL REFERENCES payroll_items(id),
    amount          numeric(14,2) NOT NULL CHECK (amount > 0),
    created_at      timestamptz   NOT NULL DEFAULT now(),
    CONSTRAINT staff_loan_repayments_loan_item_uq UNIQUE (loan_id, payroll_item_id)
);

CREATE INDEX IF NOT EXISTS staff_loan_repayments_item_idx ON staff_loan_repayments (payroll_item_id);

-- Loan installment taken from this payroll line
ALTER TABLE payroll_items ADD COLUMN IF NOT EXISTS loan_deduction numeric(14,2) NOT NULL DEFAULT 0;

COMMIT;
