-- Wallet transactions ledger: one row for every change of a wallet balance (money in / money out).
-- Written by LedgerService.move(...) from now on; this script creates the table and backfills
-- the history that already exists (opening balances, invoice payments, staff advances, payroll
-- payouts, transfers and their voids).
--
-- Run once:  psql "$DATABASE_URL" -f backend/scripts/migrations/2026-10-07_wallet_transactions.sql
-- Safe to re-run: the table is created only if missing and the backfill runs only while it is empty.

BEGIN;

CREATE TABLE IF NOT EXISTS wallet_transactions (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wallet_id     bigint        NOT NULL REFERENCES wallets(id),
    direction     varchar(3)    NOT NULL CHECK (direction IN ('in', 'out')),
    amount        numeric(14,2) NOT NULL CHECK (amount > 0),
    currency      varchar(3)    NOT NULL,
    -- Wallet balance right after this movement; NULL for backfilled rows (not known for the past)
    balance_after numeric(14,2),
    -- opening | income | purchase | expense | payment | salary | advance | transfer | request | void
    kind          varchar(20)   NOT NULL,
    -- What caused it: invoice | transfer | wallet (opening balance)
    ref_type      varchar(20),
    ref_id        bigint,
    description   text,
    -- Business date of the movement (invoice date, transfer date, today for voids)
    txn_date      date          NOT NULL,
    created_by    bigint REFERENCES users(id),
    created_at    timestamptz   NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS wallet_transactions_date_idx   ON wallet_transactions (txn_date DESC, created_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS wallet_transactions_wallet_idx ON wallet_transactions (wallet_id, created_at DESC);
CREATE INDEX IF NOT EXISTS wallet_transactions_ref_idx    ON wallet_transactions (ref_type, ref_id);

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM wallet_transactions) THEN
        RAISE NOTICE 'wallet_transactions already has rows: backfill skipped';
        RETURN;
    END IF;

    -- 1. Opening balances
    INSERT INTO wallet_transactions (wallet_id, direction, amount, currency, kind, ref_type, ref_id, description, txn_date, created_at)
    SELECT w.id, 'in', w.opening_balance, w.currency::text, 'opening', 'wallet', w.id,
           'សមតុល្យដើម · ' || w.name_km,
           (w.created_at AT TIME ZONE 'Asia/Phnom_Penh')::date, w.created_at
    FROM wallets w
    WHERE w.opening_balance > 0;

    -- 2. Invoice payments (income in; purchases, small expenses, supplier payments out)
    INSERT INTO wallet_transactions (wallet_id, direction, amount, currency, kind, ref_type, ref_id, description, txn_date, created_by, created_at)
    SELECT p.wallet_id,
           CASE WHEN i.type = 'income' THEN 'in' ELSE 'out' END,
           p.amount, p.currency,
           CASE WHEN i.type = 'income' THEN 'income'
                WHEN i.expense_kind = 'salary' THEN 'salary'
                WHEN i.expense_kind = 'product' THEN 'purchase'
                ELSE 'expense' END,
           'invoice', i.id,
           COALESCE(NULLIF(CONCAT_WS(' · ', i.table_name, NULLIF(i.supplier_name, i.table_name), i.category_name), ''), i.invoice_no),
           CASE WHEN (p.paid_at AT TIME ZONE 'Asia/Phnom_Penh')::date > i.invoice_date
                THEN (p.paid_at AT TIME ZONE 'Asia/Phnom_Penh')::date ELSE i.invoice_date END,
           COALESCE(p.created_by, i.created_by), p.paid_at
    FROM invoice_payments p
    JOIN invoices i ON i.id = p.invoice_id;

    -- 3. Staff advances (they create an invoice but no invoice_payment)
    INSERT INTO wallet_transactions (wallet_id, direction, amount, currency, kind, ref_type, ref_id, description, txn_date, created_by, created_at)
    SELECT a.wallet_id, 'out', a.amount, a.currency::text, 'advance', 'invoice', a.invoice_id,
           'បុរេប្រទាន · ' || s.name, a.given_at, a.created_by, a.created_at
    FROM staff_advances a
    JOIN staff s ON s.id = a.staff_id
    WHERE a.wallet_id IS NOT NULL
      AND NOT EXISTS (SELECT 1 FROM invoice_payments p WHERE p.invoice_id = a.invoice_id);

    -- 4. Payroll payouts (#PAY-<run>-<cur> invoices, no invoice_payment; wallet by code)
    INSERT INTO wallet_transactions (wallet_id, direction, amount, currency, kind, ref_type, ref_id, description, txn_date, created_by, created_at)
    SELECT w.id, 'out',
           CASE WHEN i.paid_usd > 0 THEN i.paid_usd ELSE i.paid_khr END,
           CASE WHEN i.paid_usd > 0 THEN 'USD' ELSE 'KHR' END,
           'salary', 'invoice', i.id,
           COALESCE(i.supplier_name, i.invoice_no), i.invoice_date, i.created_by, i.created_at
    FROM invoices i
    JOIN wallets w ON w.code = i.wallet_code
    WHERE i.expense_kind = 'salary' AND i.invoice_no LIKE '#PAY-%'
      AND (i.paid_usd > 0 OR i.paid_khr > 0)
      AND NOT EXISTS (SELECT 1 FROM invoice_payments p WHERE p.invoice_id = i.id);

    -- 5. Voids give the money back (one reversal per row above that belongs to a voided invoice)
    INSERT INTO wallet_transactions (wallet_id, direction, amount, currency, kind, ref_type, ref_id, description, txn_date, created_by, created_at)
    SELECT t.wallet_id,
           CASE WHEN t.direction = 'in' THEN 'out' ELSE 'in' END,
           t.amount, t.currency, 'void', 'invoice', i.id,
           'លុប ' || i.invoice_no || COALESCE(' · ' || NULLIF(i.void_reason, ''), ''),
           COALESCE((i.voided_at AT TIME ZONE 'Asia/Phnom_Penh')::date, t.txn_date),
           i.voided_by, COALESCE(i.voided_at, t.created_at)
    FROM wallet_transactions t
    JOIN invoices i ON i.id = t.ref_id
    WHERE t.ref_type = 'invoice' AND i.status = 'void';

    -- 6. Transfers (money requests are transfers with request_id): out of one wallet, into the other
    INSERT INTO wallet_transactions (wallet_id, direction, amount, currency, kind, ref_type, ref_id, description, txn_date, created_by, created_at)
    SELECT t.from_wallet_id, 'out', t.amount, t.currency,
           CASE WHEN t.request_id IS NOT NULL THEN 'request' ELSE 'transfer' END,
           'transfer', t.id,
           'ផ្ទេរទៅ ' || tw.name_km || COALESCE(' · ' || NULLIF(t.note, ''), ''),
           t.transfer_date, t.created_by, t.created_at
    FROM transfers t
    JOIN wallets tw ON tw.id = t.to_wallet_id;

    INSERT INTO wallet_transactions (wallet_id, direction, amount, currency, kind, ref_type, ref_id, description, txn_date, created_by, created_at)
    SELECT t.to_wallet_id, 'in', t.amount, t.currency,
           CASE WHEN t.request_id IS NOT NULL THEN 'request' ELSE 'transfer' END,
           'transfer', t.id,
           'ផ្ទេរពី ' || fw.name_km || COALESCE(' · ' || NULLIF(t.note, ''), ''),
           t.transfer_date, t.created_by, t.created_at
    FROM transfers t
    JOIN wallets fw ON fw.id = t.from_wallet_id;
END $$;

COMMIT;

-- Check: rows per kind
SELECT kind, direction, currency, COUNT(*) AS rows, SUM(amount) AS amount
FROM wallet_transactions GROUP BY 1, 2, 3 ORDER BY 1, 2, 3;

-- Check: does each wallet's ledger add up to its balance? (difference = movements made before the ledger
-- that left no record, e.g. old balance edits)
SELECT w.code, w.currency, w.current_balance,
       COALESCE(SUM(CASE WHEN t.direction = 'in' THEN t.amount ELSE -t.amount END), 0) AS ledger_sum,
       w.current_balance - COALESCE(SUM(CASE WHEN t.direction = 'in' THEN t.amount ELSE -t.amount END), 0) AS difference
FROM wallets w LEFT JOIN wallet_transactions t ON t.wallet_id = w.id
GROUP BY w.id ORDER BY w.id;
