CREATE TYPE "public"."currency_code" AS ENUM('USD', 'KHR');--> statement-breakpoint
CREATE TABLE "restaurant_tables" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "restaurant_tables_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" varchar(100) NOT NULL,
	"code" varchar(50),
	"capacity" integer,
	"status" varchar(30) DEFAULT 'available' NOT NULL,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "restaurant_tables_name_unique" UNIQUE("name")
);
--> statement-breakpoint
ALTER TABLE "wallets" ADD COLUMN "currency" "currency_code" DEFAULT 'USD' NOT NULL;--> statement-breakpoint
ALTER TABLE "wallets" ADD COLUMN "opening_balance" numeric(14, 2) DEFAULT '0.00' NOT NULL;--> statement-breakpoint
ALTER TABLE "wallets" ADD COLUMN "current_balance" numeric(14, 2) DEFAULT '0.00' NOT NULL;--> statement-breakpoint
ALTER TABLE "invoices" ADD COLUMN "table_name" varchar(50);--> statement-breakpoint
ALTER TABLE "wallets" DROP COLUMN "opening_usd";--> statement-breakpoint
ALTER TABLE "wallets" DROP COLUMN "opening_khr";--> statement-breakpoint
ALTER TABLE "wallets" DROP COLUMN "current_usd";--> statement-breakpoint
ALTER TABLE "wallets" DROP COLUMN "current_khr";