import { pool } from './index.js';
import { logger } from '../lib/logger.js';

export async function seedDatabase() {
  const client = await pool.connect();
  try {
    logger.info('🌱 Starting database seed...');
    await client.query('BEGIN');

    // 1. Wallets
    await client.query(`
      INSERT INTO wallets (code, name_km, name_en, type, category, currency, opening_balance, current_balance) VALUES
        ('drawer_usd', 'ថតលុយ (USD)', 'Cash Drawer (USD)', 'cash_drawer', 'cash', 'USD', 186.00, 186.00),
        ('drawer_khr', 'ថតលុយ (KHR)', 'Cash Drawer (KHR)', 'cash_drawer', 'cash', 'KHR', 420000.00, 420000.00),
        ('petty_usd', 'លុយចាយប្រចាំថ្ងៃ (USD)', 'Petty Cash (USD)', 'petty_cash', 'cash', 'USD', 40.00, 40.00),
        ('petty_khr', 'លុយចាយប្រចាំថ្ងៃ (KHR)', 'Petty Cash (KHR)', 'petty_cash', 'cash', 'KHR', 95000.00, 95000.00),
        ('aba_usd', 'ABA (USD)', 'ABA Bank (USD)', 'bank', 'bank', 'USD', 1240.55, 1240.55),
        ('aba_khr', 'ABA (KHR)', 'ABA Bank (KHR)', 'bank', 'bank', 'KHR', 2450000.00, 2450000.00),
        ('bakong_usd', 'បាគង KHQR (USD)', 'Bakong / KHQR (USD)', 'bank', 'bank', 'USD', 350.00, 350.00),
        ('bakong_khr', 'បាគង KHQR (KHR)', 'Bakong / KHQR (KHR)', 'bank', 'bank', 'KHR', 850000.00, 850000.00),
        ('mgr_usd', 'លុយអ្នកគ្រប់គ្រង (USD)', 'Manager Advance (USD)', 'manager_advance', 'advance', 'USD', 0.00, 0.00),
        ('mgr_khr', 'លុយអ្នកគ្រប់គ្រង (KHR)', 'Manager Advance (KHR)', 'manager_advance', 'advance', 'KHR', 0.00, 0.00)
      ON CONFLICT (code) DO NOTHING;
    `);

    // 2. Categories
    await client.query(`
      INSERT INTO categories (name_km, name_en, type, icon) VALUES
        ('គ្រឿងផ្សំ', 'Ingredients', 'expense', 'cart'),
        ('ទឹកកក', 'Ice', 'expense', 'ice'),
        ('ហ្គាស', 'Gas', 'expense', 'flame'),
        ('បុគ្គលិក', 'Staff', 'expense', 'user'),
        ('ជួសជុល', 'Repairs', 'expense', 'wrench'),
        ('ចំណូលលក់', 'Sales Income', 'income', 'income')
      ON CONFLICT DO NOTHING;
    `);

    // 3. Suppliers
    await client.query(`
      INSERT INTO suppliers (name, market_location, contact_phone) VALUES
        ('ហាងសាច់ ផ្សារថ្មី', 'ផ្សារថ្មី', '012 345 678'),
        ('ហាងអង្ករ មីងស្រី', 'ផ្សារថ្មី', '098 765 432'),
        ('ហាងបន្លែ ផ្សារដើមគរ', 'ផ្សារដើមគរ', '011 223 344'),
        ('ហាងគ្រឿងទេស បងណារី', 'ផ្សារថ្មី', '077 889 900'),
        ('ហាងទឹកកក សុខលី', 'ផ្សារថ្មី', '015 667 788'),
        ('ហាងភេសជ្ជៈ ដារ៉ា', 'ផ្សារថ្មី', '089 112 233')
      ON CONFLICT DO NOTHING;
    `);

    // 4. Products
    await client.query(`
      INSERT INTO products (name, default_unit, default_currency, default_unit_price) VALUES
        ('ប្រេងឆា', 'ដប', 'USD', 6.00),
        ('បន្លែស្រស់', 'គីឡូ', 'KHR', 3000),
        ('ស៊ុតមាន់', 'គ្រាប់', 'KHR', 500),
        ('ទឹកត្រី', 'ដប', 'USD', 1.25),
        ('សាច់ជ្រូក', 'គីឡូ', 'USD', 4.75),
        ('សាច់មាន់', 'គីឡូ', 'USD', 3.50)
      ON CONFLICT DO NOTHING;
    `);

    // 5. Default Users
    await client.query(`
      INSERT INTO users (username, name, phone, password_hash, role) VALUES
        ('somnang', 'Somnang (Owner)', '012999001', '$2b$10$P2FbujORMGFwA44HHGTI0.UAArejRWWq6rm.5IRbHPyRpyZf7ZVIO', 'owner')
      ON CONFLICT (username) DO NOTHING;
    `);

    // 6. Restaurant Tables
    await client.query(`
      CREATE TABLE IF NOT EXISTS restaurant_tables (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name VARCHAR(100) NOT NULL UNIQUE,
        code VARCHAR(50),
        capacity INTEGER,
        status VARCHAR(30) DEFAULT 'available' NOT NULL,
        sort_order INTEGER DEFAULT 0 NOT NULL,
        is_active BOOLEAN DEFAULT TRUE NOT NULL,
        created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
        updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
      );
      INSERT INTO restaurant_tables (name, code, sort_order) VALUES
        ('តុ 1', 'T01', 1), ('តុ 2', 'T02', 2), ('តុ 3', 'T03', 3), ('តុ 4', 'T04', 4),
        ('តុ 5', 'T05', 5), ('តុ 6', 'T06', 6), ('តុ 7', 'T07', 7), ('តុ 8', 'T08', 8),
        ('តុ 9', 'T09', 9), ('តុ 10', 'T10', 10), ('តុ 11', 'T11', 11), ('តុ 12', 'T12', 12),
        ('តុ VIP 1', 'VIP1', 13), ('តុ VIP 2', 'VIP2', 14),
        ('ខ្ចប់ (Takeaway)', 'TAKEAWAY', 15), ('Delivery', 'DELIVERY', 16)
      ON CONFLICT (name) DO NOTHING;
    `);

    await client.query('COMMIT');
    logger.info('✅ Database seeded successfully!');
  } catch (err: any) {
    await client.query('ROLLBACK');
    logger.error('❌ Failed seeding database:', err.message);
    throw err;
  } finally {
    client.release();
  }
}

if (process.argv[1]?.endsWith('seed.ts') || process.argv[1]?.endsWith('seed.js')) {
  seedDatabase()
    .then(() => process.exit(0))
    .catch(() => process.exit(1));
}
