-- ==============================================================================
-- Bonchi RMS: PostgreSQL & PostgREST Database Initialization Script
-- Supports: Native PostgreSQL, PostgREST 12+, Row Level Security (RLS), JWT & Local Auth
-- ==============================================================================

-- 1. Create PostgREST User Roles
DO $$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'anon') THEN
        CREATE ROLE anon NOLOGIN;
    END IF;
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'authenticated') THEN
        CREATE ROLE authenticated NOLOGIN;
    END IF;
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'bonchi_owner') THEN
        CREATE ROLE bonchi_owner NOLOGIN IN ROLE authenticated;
    END IF;
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'bonchi_manager') THEN
        CREATE ROLE bonchi_manager NOLOGIN IN ROLE authenticated;
    END IF;
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'bonchi_staff') THEN
        CREATE ROLE bonchi_staff NOLOGIN IN ROLE authenticated;
    END IF;
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'authenticator') THEN
        CREATE ROLE authenticator NOINHERIT LOGIN PASSWORD 'bonchi_authenticator_secret_2026';
    END IF;
END $$;

GRANT anon TO authenticator;
GRANT authenticated TO authenticator;
GRANT bonchi_owner TO authenticator;
GRANT bonchi_manager TO authenticator;
GRANT bonchi_staff TO authenticator;

-- 2. Schema Privileges
GRANT USAGE ON SCHEMA public TO anon, authenticated, bonchi_owner, bonchi_manager, bonchi_staff;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE ON TABLES TO authenticated, bonchi_owner, bonchi_manager;

-- 3. Extensions
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- 4. Custom Enum Types (Idempotent)
DO $$ BEGIN CREATE TYPE user_role AS ENUM ('owner', 'manager', 'staff'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE category_type AS ENUM ('income', 'expense'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE wallet_type AS ENUM ('cash', 'bank', 'cash_drawer', 'petty_cash', 'delivery_app', 'staff_advance', 'manager_advance', 'tips'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE invoice_type AS ENUM ('expense', 'income'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE expense_kind AS ENUM ('product', 'small'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE invoice_status AS ENUM ('paid', 'partial', 'unpaid', 'void'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE payment_method AS ENUM ('cash', 'qr', 'bank_transfer', 'credit'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE request_status AS ENUM ('pending', 'approved', 'rejected', 'settled'); EXCEPTION WHEN duplicate_object THEN null; END $$;

-- 5. Helper functions for PostgREST JWT claims
DROP FUNCTION IF EXISTS current_user_id() CASCADE;
DROP FUNCTION IF EXISTS request_jwt_claim(TEXT) CASCADE;
DROP FUNCTION IF EXISTS current_user_role() CASCADE;

CREATE OR REPLACE FUNCTION request_jwt_claim(claim TEXT) RETURNS TEXT AS $$
    SELECT NULLIF(current_setting('request.jwt.claims', true)::jsonb ->> claim, '');
$$ LANGUAGE SQL STABLE;

CREATE OR REPLACE FUNCTION current_user_id() RETURNS BIGINT AS $$
    SELECT NULLIF(current_setting('request.jwt.claims', true)::jsonb ->> 'sub', '')::BIGINT;
$$ LANGUAGE SQL STABLE;

CREATE OR REPLACE FUNCTION current_user_role() RETURNS TEXT AS $$
    SELECT NULLIF(current_setting('request.jwt.claims', true)::jsonb ->> 'role', '');
$$ LANGUAGE SQL STABLE;

-- 6. Tables Definition (All Primary Keys use BIGINT)
DROP TABLE IF EXISTS audit_log CASCADE;
DROP TABLE IF EXISTS request_distributions CASCADE;
DROP TABLE IF EXISTS money_requests CASCADE;
DROP TABLE IF EXISTS wallet_counts CASCADE;
DROP TABLE IF EXISTS transfers CASCADE;
DROP TABLE IF EXISTS invoice_payments CASCADE;
DROP TABLE IF EXISTS invoice_items CASCADE;
DROP TABLE IF EXISTS invoices CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS suppliers CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS wallets CASCADE;
DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) UNIQUE NOT NULL,
    name VARCHAR(100) NOT NULL,
    phone VARCHAR(20),
    password_hash VARCHAR(255) NOT NULL,
    avatar_url TEXT,
    role user_role NOT NULL DEFAULT 'staff',
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_km VARCHAR(100) NOT NULL,
    name_en VARCHAR(100),
    type category_type NOT NULL,
    parent_id BIGINT REFERENCES categories(id) ON DELETE SET NULL,
    icon VARCHAR(50),
    is_active BOOLEAN NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS suppliers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    market_location VARCHAR(100),
    contact_phone VARCHAR(50),
    note TEXT,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    default_unit VARCHAR(50) NOT NULL,
    category_id BIGINT REFERENCES categories(id) ON DELETE RESTRICT,
    supplier_id BIGINT REFERENCES suppliers(id) ON DELETE SET NULL,
    default_currency VARCHAR(3) CHECK (default_currency IN ('USD', 'KHR')),
    default_unit_price DECIMAL(14,2) DEFAULT 0,
    is_active BOOLEAN NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS wallets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) UNIQUE NOT NULL,
    name_km VARCHAR(100) NOT NULL,
    name_en VARCHAR(100) NOT NULL,
    type wallet_type NOT NULL,
    category VARCHAR(20) NOT NULL DEFAULT 'cash' CHECK (category IN ('cash', 'bank', 'advance', 'other')),
    opening_usd DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    opening_khr DECIMAL(14,0) NOT NULL DEFAULT 0,
    current_usd DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    current_khr DECIMAL(14,0) NOT NULL DEFAULT 0,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS invoices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_no VARCHAR(50) UNIQUE NOT NULL,
    invoice_date DATE NOT NULL DEFAULT CURRENT_DATE,
    invoice_time TIME NOT NULL DEFAULT CURRENT_TIME,
    type invoice_type NOT NULL DEFAULT 'expense',
    expense_kind expense_kind,
    market_trip_id BIGINT,
    supplier_id BIGINT REFERENCES suppliers(id) ON DELETE RESTRICT,
    supplier_name VARCHAR(150),
    category_id BIGINT REFERENCES categories(id) ON DELETE RESTRICT,
    category_name VARCHAR(100),
    wallet_code VARCHAR(50),
    total_usd DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    total_khr DECIMAL(14,0) NOT NULL DEFAULT 0,
    paid_usd DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    paid_khr DECIMAL(14,0) NOT NULL DEFAULT 0,
    status invoice_status NOT NULL DEFAULT 'paid',
    void_reason VARCHAR(100),
    voided_by BIGINT REFERENCES users(id),
    voided_at TIMESTAMPTZ,
    receipt_url TEXT,
    note TEXT,
    created_by BIGINT REFERENCES users(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS invoice_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id BIGINT NOT NULL REFERENCES invoices(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES products(id) ON DELETE RESTRICT,
    item_name VARCHAR(150) NOT NULL,
    quantity DECIMAL(10,3) NOT NULL CHECK (quantity > 0),
    unit VARCHAR(50) NOT NULL,
    unit_price DECIMAL(14,2) NOT NULL CHECK (unit_price >= 0),
    currency VARCHAR(3) NOT NULL CHECK (currency IN ('USD', 'KHR')),
    line_total DECIMAL(14,2) NOT NULL CHECK (line_total >= 0),
    is_paid BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS invoice_payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id BIGINT NOT NULL REFERENCES invoices(id) ON DELETE CASCADE,
    wallet_id BIGINT NOT NULL REFERENCES wallets(id) ON DELETE RESTRICT,
    amount DECIMAL(14,2) NOT NULL CHECK (amount > 0),
    currency VARCHAR(3) NOT NULL CHECK (currency IN ('USD', 'KHR')),
    method payment_method NOT NULL DEFAULT 'cash',
    cross_currency_rate DECIMAL(10,4),
    paid_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by BIGINT REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS transfers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transfer_date DATE NOT NULL DEFAULT CURRENT_DATE,
    from_wallet_id BIGINT NOT NULL REFERENCES wallets(id) ON DELETE RESTRICT,
    to_wallet_id BIGINT NOT NULL REFERENCES wallets(id) ON DELETE RESTRICT,
    amount DECIMAL(14,2) NOT NULL CHECK (amount > 0),
    currency VARCHAR(3) NOT NULL CHECK (currency IN ('USD', 'KHR')),
    note TEXT,
    request_id BIGINT,
    created_by BIGINT REFERENCES users(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS wallet_counts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wallet_id BIGINT NOT NULL REFERENCES wallets(id) ON DELETE RESTRICT,
    currency VARCHAR(3) NOT NULL CHECK (currency IN ('USD', 'KHR')),
    count_date DATE NOT NULL DEFAULT CURRENT_DATE,
    system_amount DECIMAL(14,2) NOT NULL,
    counted_amount DECIMAL(14,2) NOT NULL,
    difference DECIMAL(14,2) GENERATED ALWAYS AS (counted_amount - system_amount) STORED,
    tolerance_threshold DECIMAL(14,2) NOT NULL,
    denominations_breakdown JSONB NOT NULL,
    reason_for_gap TEXT,
    is_blind_count BOOLEAN NOT NULL DEFAULT true,
    counted_by BIGINT REFERENCES users(id),
    verified_by BIGINT REFERENCES users(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS money_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requested_by BIGINT NOT NULL REFERENCES users(id),
    amount DECIMAL(14,2) NOT NULL CHECK (amount > 0),
    currency VARCHAR(3) NOT NULL CHECK (currency IN ('USD', 'KHR')),
    category_id BIGINT REFERENCES categories(id) ON DELETE RESTRICT,
    reason TEXT NOT NULL,
    status request_status NOT NULL DEFAULT 'pending',
    approved_by BIGINT REFERENCES users(id),
    approved_at TIMESTAMPTZ,
    rejection_reason TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS request_distributions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id BIGINT NOT NULL REFERENCES money_requests(id) ON DELETE CASCADE,
    recipient_name VARCHAR(100) NOT NULL,
    amount DECIMAL(14,2) NOT NULL CHECK (amount > 0),
    currency VARCHAR(3) NOT NULL CHECK (currency IN ('USD', 'KHR')),
    given_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    note TEXT
);

CREATE TABLE IF NOT EXISTS audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_name VARCHAR(50) NOT NULL,
    record_id BIGINT NOT NULL,
    action VARCHAR(20) NOT NULL,
    old_value JSONB,
    new_value JSONB,
    user_id BIGINT REFERENCES users(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Sequence privileges for PostgREST & Authenticated Roles
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, bonchi_owner, bonchi_manager, bonchi_staff;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO authenticated, bonchi_owner, bonchi_manager, bonchi_staff;

-- 7. Row Level Security (RLS) Configuration for PostgREST & PostgreSQL
ALTER TABLE wallets ENABLE ROW LEVEL SECURITY;
ALTER TABLE invoices ENABLE ROW LEVEL SECURITY;
ALTER TABLE wallet_counts ENABLE ROW LEVEL SECURITY;

-- Wallet RLS Policies:
-- Owners see all wallets
DROP POLICY IF EXISTS wallets_owner_all ON wallets;
CREATE POLICY wallets_owner_all ON wallets
    FOR ALL TO bonchi_owner USING (true);

-- Managers see Cash Drawer & Petty Cash
DROP POLICY IF EXISTS wallets_manager_select ON wallets;
CREATE POLICY wallets_manager_select ON wallets
    FOR SELECT TO bonchi_manager
    USING (code IN ('drawer', 'petty', 'mgr', 'aba', 'bakong'));

-- Staff only see Petty Cash
DROP POLICY IF EXISTS wallets_staff_select ON wallets;
CREATE POLICY wallets_staff_select ON wallets
    FOR SELECT TO bonchi_staff
    USING (code IN ('petty'));

-- Invoices RLS Policies:
DROP POLICY IF EXISTS invoices_owner_all ON invoices;
CREATE POLICY invoices_owner_all ON invoices
    FOR ALL TO bonchi_owner USING (true);

DROP POLICY IF EXISTS invoices_manager_select_insert ON invoices;
CREATE POLICY invoices_manager_select_insert ON invoices
    FOR ALL TO bonchi_manager USING (true);

DROP POLICY IF EXISTS invoices_staff_insert ON invoices;
CREATE POLICY invoices_staff_insert ON invoices
    FOR INSERT TO bonchi_staff WITH CHECK (true);

DROP POLICY IF EXISTS invoices_staff_select ON invoices;
CREATE POLICY invoices_staff_select ON invoices
    FOR SELECT TO bonchi_staff USING (created_by = current_user_id() OR invoice_date = CURRENT_DATE);

-- 8. Seed Default Master Data
INSERT INTO wallets (code, name_km, name_en, type, category, opening_usd, opening_khr, current_usd, current_khr) VALUES
    ('drawer', 'ថតលុយ', 'Cash drawer', 'cash_drawer', 'cash', 186.00, 420000, 186.00, 420000),
    ('petty', 'លុយចាយប្រចាំថ្ងៃ', 'Petty cash', 'petty_cash', 'cash', 40.00, 95000, 40.00, 95000),
    ('aba', 'ABA', 'ABA Bank', 'bank', 'bank', 1240.55, 2450000, 1240.55, 2450000),
    ('bakong', 'បាគង KHQR', 'Bakong / KHQR', 'bank', 'bank', 350.00, 850000, 350.00, 850000),
    ('mgr', 'លុយអ្នកគ្រប់គ្រង', 'Manager advance', 'manager_advance', 'advance', 0.00, 0, 0.00, 0)
ON CONFLICT (code) DO NOTHING;

INSERT INTO categories (name_km, name_en, type, icon) VALUES
    ('គ្រឿងផ្សំ', 'Ingredients', 'expense', 'cart'),
    ('ទឹកកក', 'Ice', 'expense', 'ice'),
    ('ហ្គាស', 'Gas', 'expense', 'flame'),
    ('បុគ្គលិក', 'Staff', 'expense', 'user'),
    ('ជួសជុល', 'Repairs', 'expense', 'wrench'),
    ('ចំណូលលក់', 'Sales Income', 'income', 'income')
ON CONFLICT DO NOTHING;

INSERT INTO suppliers (name, market_location, contact_phone) VALUES
    ('ហាងសាច់ ផ្សារថ្មី', 'ផ្សារថ្មី', '012 345 678'),
    ('ហាងអង្ករ មីងស្រី', 'ផ្សារថ្មី', '098 765 432'),
    ('ហាងបន្លែ ផ្សារដើមគរ', 'ផ្សារដើមគរ', '011 223 344'),
    ('ហាងគ្រឿងទេស បងណារី', 'ផ្សារថ្មី', '077 889 900'),
    ('ហាងទឹកកក សុខលី', 'ផ្សារថ្មី', '015 667 788'),
    ('ហាងភេសជ្ជៈ ដារ៉ា', 'ផ្សារថ្មី', '089 112 233')
ON CONFLICT DO NOTHING;

INSERT INTO products (name, default_unit, default_currency, default_unit_price) VALUES
    ('ប្រេងឆា', 'ដប', 'USD', 6.00),
    ('បន្លែស្រស់', 'គីឡូ', 'KHR', 3000),
    ('ស៊ុតមាន់', 'គ្រាប់', 'KHR', 500),
    ('ទឹកត្រី', 'ដប', 'USD', 1.25),
    ('សាច់ជ្រូក', 'គីឡូ', 'USD', 4.75),
    ('សាច់មាន់', 'គីឡូ', 'USD', 3.50)
ON CONFLICT DO NOTHING;

-- Default Owner User (Password: bonchi2026, login via username & password)
INSERT INTO users (username, name, phone, password_hash, role) VALUES
    ('owner', 'Lok Bong (Owner)', '012999001', '$2b$10$fnTYczk0J.r5vwincO8sVucm5rv9TGsUioW2MzNgrK1sbBju1uCfW', 'owner'),
    ('manager', 'Sokha (Manager)', '012999002', '$2b$10$fnTYczk0J.r5vwincO8sVucm5rv9TGsUioW2MzNgrK1sbBju1uCfW', 'manager'),
    ('staff', 'Srey Mom (Staff)', '012999003', '$2b$10$fnTYczk0J.r5vwincO8sVucm5rv9TGsUioW2MzNgrK1sbBju1uCfW', 'staff')
ON CONFLICT (username) DO UPDATE SET password_hash = EXCLUDED.password_hash;

-- Initial Real Invoices
INSERT INTO invoices (invoice_no, invoice_date, invoice_time, type, expense_kind, supplier_name, category_name, wallet_code, total_usd, total_khr, paid_usd, paid_khr, status) VALUES
    ('#0412', CURRENT_DATE, '07:40', 'expense', 'product', 'ហាងសាច់ ផ្សារថ្មី', 'គ្រឿងផ្សំ', 'petty', 47.00, 55000, 47.00, 55000, 'paid'),
    ('#0413', CURRENT_DATE, '09:15', 'expense', 'small', 'អ្នកផ្គត់ផ្គង់ទឹកកក', 'ទឹកកក', 'petty', 0.00, 8000, 0.00, 8000, 'paid'),
    ('#0414', CURRENT_DATE, '13:10', 'income', NULL, 'Grab Delivery', 'ចំណូលលក់', 'aba', 63.20, 0, 63.20, 0, 'paid'),
    ('#0415', CURRENT_DATE, '14:20', 'expense', 'small', 'ហាងហ្គាស គីមហេង', 'ហ្គាស', 'drawer', 49.00, 0, 49.00, 0, 'paid')
ON CONFLICT (invoice_no) DO NOTHING;

-- Initial Transfers
INSERT INTO transfers (transfer_date, from_wallet_id, to_wallet_id, amount, currency, note)
SELECT CURRENT_DATE, w1.id, w2.id, 100.00, 'USD', 'Top up petty cash from cash drawer'
FROM wallets w1, wallets w2
WHERE w1.code = 'drawer' AND w2.code = 'petty'
LIMIT 1;
